name: lost_and_found
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.8
  intl_translation: ^0.17.7
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+8
  cloud_firestore: ^0.12.10
  firebase_storage: ^3.0.8
  shared_preferences: ^0.5.3+4
  flushbar: ^1.9.1
  datetime_picker_formfield: ^0.4.3
  image_picker: ^0.6.1+11
  cached_network_image: ^1.1.3
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/background.jpg
    - images/logo.png